before_script:
  - npm install -g gulp

script: gulp

language: node_js

node_js:
- "0.10"
- "0.12"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
